# Build Zotero plugin.

name: Build Zotero Swisscovery UB Bern plugin

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build-plugin:
    name: Build and release plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 50
          fetch-tags: true

      - name: Setup git
        run: git config --global user.email "ci@example.com" && git config --global user.name "GitHub CI"
      
      - name: Test
        run: echo "Are we here?"
      
      - name: Show Tag
        run: echo $(git describe --tags || echo ci-test)
      
    #   - name: Install dependencies
    #     run: sudo apt update && sudo apt install jq

    #   - name: Echo tag version
    #     run: echo $(git describe --tags || echo ci-test)

    #   - name: Run build
    #     run: ./build.sh $(git describe --tags || echo ci-test)

    #   - name: Prepare Update Manifests
    #     run: ./publish.sh $(git describe --tags || echo ci-test )

    #   - uses: actions/upload-artifact@v4
    #     with:
    #       name: Zotero Swisscovery UB Bern plugin (zipped)
    #       path: "build/*.xpi"
