# Build Zotero plugin.

name: Build Zotero Swisscovery UB Bern plugin

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build-plugin:
    name: Build and release plugin
    runs-on: ubuntu-latest
    env:
      version: $(git describe --tags || echo ci-test)
      assetname: zotero-swisscovery-ubbern-locations
      updatelink: https://github.com/ub-unibe-ch/zotero-swissbib-bb-locations/releases/download/${version}/${assetname}-${version}.xpi

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup git
        run: git config --global user.email "ci@example.com" && git config --global user.name "GitHub CI"
      
      - name: Install dependencies
        run: sudo apt update && sudo apt install jq

      - name: Run build
        run: |
          mkdir build
          # zip -r build/${assetname}-${version}.xpi src/*
          zip -r build/test.xpi src/*

      - name: Prepare Update Manifests
        run: |
          jq ".addons[\"zoteroswisscoveryubbernlocations@ubbe.org\"].updates[0].update_hash = \"sha256:`shasum -a 256 build/${assetname}-${version}.xpi | cut -d' ' -f1`\"" updates.json.tmpl |
          jq --arg version "$version" '.addons["zoteroswisscoveryubbernlocations@ubbe.org"].updates[0].version = $version' |
          jq --arg updatelink "$updatelink" '.addons["zoteroswisscoveryubbernlocations@ubbe.org"].updates[0].update_link = $updatelink' > updates.json
          cp updates.json update.rdf

      - name: Publish release
        run: |
          git add src/install.rdf src/manifest.json update.rdf updates.json
          git commit -m "Release $version" 1>&2
          git tag -a -m "Release $version" "$version"

      - uses: actions/upload-artifact@v4
        with:
          name: Zotero Swisscovery UB Bern plugin (zipped)
          path: "build/*.xpi"
